#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Haplocheirus
  class TimelineStoreException < ::Thrift::Exception
    include ::Thrift::Struct
    def initialize(message=nil)
      super()
      self.description = message
    end

    def message; description end

    DESCRIPTION = 1

    ::Thrift::Struct.field_accessor self, :description
    FIELDS = {
      DESCRIPTION => {:type => ::Thrift::Types::STRING, :name => 'description'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class TimelineSegment
    include ::Thrift::Struct
    ENTRIES = 1
    SIZE = 2

    ::Thrift::Struct.field_accessor self, :entries, :size
    FIELDS = {
      ENTRIES => {:type => ::Thrift::Types::LIST, :name => 'entries', :element => {:type => ::Thrift::Types::STRING}},
      SIZE => {:type => ::Thrift::Types::I32, :name => 'size'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

end
