#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

module Haplocheirus
  class TimelineStoreException < ::Thrift::Exception
    include ::Thrift::Struct
    def initialize(message=nil)
      super()
      self.description = message
    end

    def message; description end

    DESCRIPTION = 1

    ::Thrift::Struct.field_accessor self, :description
    FIELDS = {
      DESCRIPTION => {:type => ::Thrift::Types::STRING, :name => 'description'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end
end
